### PR TITLE
chore(esm/cjs): review transpilation, replace node-fetch with cross-fetch

### PR DESCRIPTION
**Pull request by KaiSchwarz-cnic**

### CODE REVIEW

**Review by plorencrstit — APPROVED** [review]

**Comment by KaiSchwarz-cnic** [comment]
@plorencrstit v9.0.0 worked fine for me.

https://github.com/hexonet/node-sdk-demo (`npm run test`)

**Comment by plorencrstit** [comment]
I confirm that it works for me :) Thank you very much for this new version!

**Comment by KaiSchwarz-cnic** [comment]
Great that it works ... feels like a blackbox actually with esm/cjs in node. Looking forward to a LTS version of node supporting all this with no big issues.

**Pull request merged**
