### PR TITLE
fix: allow to import es module package into common js

### PR DESCRIPTION
**Pull request by plorencrstit**
I finally managed to import this package into my commonjs repository with one fix. All internal import need to have extensions `.js`. 

So for example in `apiclient.ts`:
```
import { Logger } from "./logger";
import { Response } from "./response";
import { ResponseTemplateManager } from "./responsetemplatemanager";
import { fixedURLEnc, SocketConfig } from "./socketconfig";
```
I changed to:
```
import { Logger } from "./logger.js";
import { Response } from "./response.js";
import { ResponseTemplateManager } from "./responsetemplatemanager.js";
import { fixedURLEnc, SocketConfig } from "./socketconfig.js";
```

and the same way I edited other files in `src` directory.

Without it I have error as:
```
Cannot find module '/Users/plorenc/projects/yourtv/yourtv-backend/node_modules/@hexonet/ispapi-apiconnector/dist/src/apiclient' imported from /Users/plorenc/projects/yourtv/yourtv-backend/node_modules/@hexonet/ispapi-apiconnector/dist/src/index.js
```

Of course to import ESM package into CJS project I need to import it using `async import`:
```
const _importDynamic = new Function('modulePath', 'return import(modulePath)');
const { APIClient } = await _importDynamic('@hexonet/ispapi-apiconnector');
this.client = new APIClient();
```
But this is good enough (the best option would be to could import this package as commonjs).

With this change I won't need to have any fork.

### CODE REVIEW

**Comment by plorencrstit** [comment]
ES Modules with typescript are tricky. Those extensions are required. 

Useful links:
- https://stackoverflow.com/questions/55251956/how-does-javascript-import-find-the-module-without-an-extension
- https://nodejs.org/api/esm.html#esm_import_specifiers
- https://bobbyhadz.com/blog/javascript-error-err-module-not-found-cannot-find-module
- https://github.com/microsoft/TypeScript/issues/42151
- https://stackoverflow.com/questions/62619058/appending-js-extension-on-relative-import-statements-during-typescript-compilat

**Comment by KaiSchwarz-cnic** [comment]
Morning @plorencrstit,

thanks for your investigation. Still, as we are in context of typescript, it is not the right way to import .js files. Especially as these .js files are getting auto-generated by our build process (transpiling). Mixing TS with JS looks weird tbh.
TS can be run standalone without JS Files in place. See here: https://github.com/hexonet/node-sdk-demo/blob/master/src/app_nosession.ts
So your PR is definitely the wrong way imho.

NestJS as far as I remember is again a non-typescript capable Framework, so you're in context of JS and have therefore to deal with the transpiled JS files (under /dist). Would you mind forwarding your nodejs version for reference?

**Comment by plorencrstit** [comment]
NestS is a typescript oriented framework.

I think you misunderstand the code. In the pull request I do not import JS files :) I know this is confusing (the .js endings), that’s why there is an endless discussion about it amongst typescript maintainers. 

In CommonJS there was no need to add extensions to the import. It is required in ES Modules. 

CommonJS:
```
const logger = require("./logger");
```

ES Modules:
```
import Logger from "./logger.js";
```

It is more complicated for typescript as TS doesn’t rewrite the path. So we can use have e.g.:
```
import Logger from "./logger.ts";
```

Even if in the code there is `import Logger from "./logger.js”;`, typescript will use `logger.ts` file!

Without this fix there is no possibility to import async this `node-sdk` package into `commonjs` project.

**Comment by KaiSchwarz-cnic** [comment]
-> #242

**Pull request closed without merging**
